// src/pages/forgot/index.tsx
import AuthCommon from '@/components/auth/AuthCommon'
import { NextPage } from 'next'
import Head from 'next/head'

const ForgotPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>암호 재발급</title>
      </Head>
      <AuthCommon mode="forgot" />
    </>
  )
}

export default ForgotPage

// src/pages/forgot.vue
<template>
  <AuthCommonForm page-mode="forgot" />
</template>

<script>
import pageBase from '~/mixins/page-base'
import AuthCommonForm from '~/components/auth/AuthCommonForm'
import autoHead from '~/modules/auto-head'

export default {
  name: 'forgot',
  components: { AuthCommonForm },
  mixins: [pageBase],
  head() {
    return {
      title: this.$t('auth.signIn'),
      meta: [...autoHead(this.$t('auth.signIn'))],
    }
  },
}
</script>
